service/pixelated/adapter/soledad/soledad_search_key_masterkey_retrieval_mixin.py, service/pixelated/support/encrypted_file_storage.py, service/test/support/integration/app_test_client.py, service/test/unit/support/encrypted_file_storage_test.py
@olabini @fbernitt Can you review this too please?
=> #227 - MAC on encrypted storage

web-ui/app/js/mail_list_actions/ui/mail_list_actions.js, web-ui/app/templates/mail_actions/actions_box.hbs
Pixelated Hackday Berlin FTW :-)
=> Issue #20: Label button 'Delete PERMANENTLY' when in trash

web-ui/app/js/search/results_highlighter.js, web-ui/karma.conf.js, web-ui/test/spec/search/results_highlighter.spec.js
Hey all!
I noticed that the file `app/js/lib/highlightRegex.js` wasn't being loaded during the test, so I added it on `karma.conf.js`. I'm not sure if it was the right thing to do though.
Thanks
=> #192 - Highlighted in results doesn't match what search engine is actually looking for

web-ui/app/templates/mails/single.hbs
Now when you list/search all emails you are able to easily identify what belongs to trash.
=> #298 [Glauco, Luiz] Including trash icon on trashed emails

service/pixelated/adapter/soledad/soledad_facade_mixin.py, service/pixelated/assets/welcome.mail, service/pixelated/config/app_factory.py, service/pixelated/config/welcome_mail.py, service/test/integration/test_welcome_mail.py, service/test/unit/config/test_welcome_mail.py
For #334
Now with message about encryption status.
=> Welcome email

web-ui/app/js/tags/ui/tag_list.js, web-ui/test/spec/tags/ui/tag_list.spec.js
Triggering events.ui.mails.uncheckAll when calling
events.ui.tag.select
refers to #289 
with @mindyor :)
=> Unchecking all emails when changing inbox

web-ui/app/js/services/model/mail.js
I was surfing the code and I got quite confused with the closures and
redefinitions of `this` when creating the mail model.
I tried to keep the style of grouping together the functions assignment
on the model on the end.
=> Makes the mail model creation more linear

web-ui/app/js/helpers/view_helper.js, web-ui/app/js/mixins/with_mail_edit_base.js, web-ui/app/js/views/i18n.js, web-ui/test/spec/helpers/view_helper.spec.js
=> Preprend messages with response information

service/pixelated/config/register.py, service/test/unit/config/test_register.py
-- Issue #147
@anikarni and @enzoz pairing
=> Validates username before request user creation on leap server

service/pixelated/adapter/listeners/mailbox_indexer_listener.py, service/pixelated/adapter/services/mailbox.py, service/pixelated/adapter/services/mailboxes.py, service/pixelated/adapter/soledad/soledad_facade_mixin.py, service/pixelated/adapter/soledad/soledad_reader_mixin.py, service/pixelated/adapter/soledad/soledad_writer_mixin.py, service/pixelated/bitmask_libraries/session.py, service/pixelated/config/welcome_mail.py, service/pixelated/maintenance.py, service/test/integration/test_search.py, service/test/support/integration/app_test_client.py, service/test/unit/maintenance/test_commands.py
Migrating it to be all async, as of our libraries in 0.7.
This is an initial draft.
All commands and sync chain is beind deferred.
Still needs a lot of fixes -- **do not merge yet**
=> [fix] migrating maintenance.py

service/pixelated/adapter/services/mail_service.py, service/pixelated/application.py, service/pixelated/config/services.py, service/pixelated/resources/root_resource.py, service/test/support/integration/app_test_client.py, service/test/unit/adapter/test_mail_service.py, service/test/unit/resources/test_root_resource.py, web-ui/app/index.html
Exposing email address to be shown in title.
=> show user email address in title

install-pixelated.sh
=> Split pip and setuptools upgrade

service/pixelated/config/site.py, service/test/unit/config/test_site.py
=> Add recommended security headers

.gitignore, README.md
From https://github.com/pixelated/pixelated-user-agent/pull/610
Followed @felixhammerl's suggestion to get rid of the merge commit.
=> README additions continued from https://github.com/pixelated/pixelated-user-agent/pull/610

web-ui/app/scss/views/_navigation.scss
[WIP] I changed the size of the Hamburger icon and made a better alignment. However I am not quite sure I put the code in the right place.
Fix #715
=> Changing icon size and margin

web-ui/app/scss/views/_compose-button.scss, web-ui/app/templates/mail_actions/compose_trigger.hbs
=> Compose now is a HTML Button

Makefile, README.md, service/go, web-ui/package.json
The python setup (including automatic creation of virtualenv) and
test runners are already working. Pending javascript build and tests
=> Creates a unified makefile for pixelated client and web-ui

service/pixelated/config/sessions.py, service/test/unit/config/test_sessions.py
=> Encodes user_uuid and passphrase to allow utf-8 characteres

web-ui/app/scss/views/_mail-list.scss
Validated with @SweetVirginia the position of ellipsis in mail list
=> Adjusts to ellipsis work correctly in mail list - Issue #829

service/pixelated/resources/__init__.py, service/pixelated/resources/login_resource.py, service/pixelated/resources/root_resource.py
Organizing a few stuff before heading to #907.
=> Authentication error

Makefile, web-ui/app/account_recovery.html, web-ui/app/js/account_recovery.js, web-ui/app/js/account_recovery/page.js, web-ui/app/scss/account_recovery/page.scss, web-ui/app/scss/base/_colors.scss, web-ui/config/loaders-webpack.js, web-ui/package.json, web-ui/test/spec/account_recovery/page.spec.js, web-ui/webpack.config.js, web-ui/webpack.production.config.js
=> [#922] Add html and css for the backup page

web-ui/.jshintignore, web-ui/package.json, web-ui/src/backup_account/app.js, web-ui/src/backup_account/backup_account.html, web-ui/src/backup_account/page.js, web-ui/test/integration/i18n.js, web-ui/test/integration/setup.js, web-ui/test/integration/translations.spec.js, web-ui/webpack.config.js, web-ui/webpack.test.config.js
We added tests for ensuring our page is being translated.
=> Integration tests for translations

service/pixelated/config/sessions.py, service/requirements.txt, service/test/support/integration/app_test_client.py
These changes were necessary to be compatible with soledad master version.
=> Changes to keep the compatibility with new soledad changes

service/test/functional/features/steps/login.py, web-ui/app/locales/en_US/translation.json, web-ui/app/locales/pt_BR/translation.json, web-ui/package.json, web-ui/src/backup_account/page.js, web-ui/src/backup_account/page.scss, web-ui/src/backup_account/page.spec.js, web-ui/src/common/input_field/input_field.js, web-ui/src/common/submit_button/submit_button.js, web-ui/src/common/submit_button/submit_button.scss, web-ui/src/common/submit_button/submit_button.spec.js, web-ui/test/integration/backup_account.spec.js
Added the validation for the email.
Also changed the submit button to use material-ui.
=> Email validation on the backup account page

web-ui/package.json, web-ui/src/backup_account/backup_account.js, web-ui/src/backup_account/backup_email/backup_email.js, web-ui/src/backup_account/backup_email/backup_email.spec.js, web-ui/src/backup_account/page.js, web-ui/src/backup_account/page.spec.js, web-ui/webpack.test.config.js
With these changes, a new recovery code will be persisted when we click on the "Add Account" button.
Related with #924
=> Update recovery code

service/pixelated/account_recovery.py, service/pixelated/resources/__init__.py, service/pixelated/resources/backup_account_resource.py, service/requirements.txt, service/test/unit/resources/test_backup_account_resource.py, service/test/unit/resources/test_base_resource.py, service/test/unit/test_account_recovery.py
Related PR in Soledad: https://0xacab.org/leap/soledad/merge_requests/72, for now we are using our branch, but it should be temporary.
Related with: #1012 .
=> Generate recovery code

service/test/functional/features/environment.py, service/test/functional/features/smoke.feature, service/test/functional/features/steps/backup_account.py, service/test/functional/features/steps/login.py, web-ui/src/common/flat_button/flat_button.js, web-ui/src/common/flat_button/flat_button.spec.js, web-ui/src/common/header/header.js, web-ui/src/common/header/header.scss, web-ui/src/common/header/header.spec.js, web-ui/src/common/logout/logout.js, web-ui/src/common/logout/logout.spec.js, web-ui/test/integration/backup_account.spec.js
This is to replace the existing logout anchor in the header with a logout button component.
TODO: Write integration tests.
=> |#973| Thais + Sriram | Adds logout component to be shown on the header

web-ui/app/js/mail_list_actions/ui/compose_trigger.js, web-ui/app/js/mail_view/ui/send_button.js, web-ui/app/js/mixins/with_mail_edit_base.js, web-ui/app/js/user_alerts/ui/user_alerts.js, web-ui/app/locales/en_US/translation.json, web-ui/app/locales/pt_BR/translation.json, web-ui/test/spec/mail_view/ui/send_button.spec.js
=> [#830] Send mail feedback

Makefile, service/test/functional/features/account_recovery.feature, service/test/functional/features/environment.py, service/test/functional/features/smoke.feature, service/test/functional/features/steps/backup_account.py, service/test/functional/features/steps/login.py, service/test/functional/features/steps/utils.py
=> [#927] Creates functional tests for backup account flow

web-ui/app/locales/en_US/translation.json, web-ui/app/locales/pt_BR/translation.json, web-ui/src/account_recovery/backup_account_step/backup_account_step.js, web-ui/src/account_recovery/backup_account_step/backup_account_step.spec.js, web-ui/src/account_recovery/new_password_form/new_password_form.js, web-ui/src/account_recovery/new_password_form/new_password_form.spec.js, web-ui/src/account_recovery/page.js, web-ui/src/account_recovery/page.spec.js, web-ui/src/common/link_button/link_button.js, web-ui/src/common/link_button/link_button.scss, web-ui/src/common/link_button/link_button.spec.js, web-ui/src/common/submit_button/submit_button.js, web-ui/test/integration/translations.spec.js
Adds a page at the end of the account recovery flow to redirect to backup account page.
Related with #938
=> Backup account at end of account recovery

web-ui/src/account_recovery/page.scss, web-ui/src/common/link_button/link_button.js, web-ui/src/common/link_button/link_button.scss, web-ui/src/common/link_button/link_button.spec.js
Fixes styling related to the link button which redirects to the backup-account page from the account recovery flow.
=> Backup account during recovery

service/pixelated/resources/account_recovery_resource.py, web-ui/app/locales/en_US/translation.json, web-ui/app/locales/pt_BR/translation.json, web-ui/src/account_recovery/new_password_form/new_password_form.js, web-ui/src/account_recovery/new_password_form/new_password_form.spec.js, web-ui/test/integration/account_recovery.spec.js
=> [#934] Add front-end password validation

service/test/functional/features/account_recovery.feature, service/test/functional/features/environment.py, service/test/functional/features/page_objects/__init__.py, service/test/functional/features/page_objects/account_recovery_page.py, service/test/functional/features/page_objects/base_page.py, service/test/functional/features/steps/account_recovery.py
Adds functional test for account recovery flow
with @anikarni
=> [#938] Adds smoke test for account recovery flow

service/pixelated/account_recovery.py, service/pixelated/assets/recovery.mail.en-US, service/test/functional/features/steps/mail_list.py, service/test/functional/features/steps/mail_view.py, service/test/unit/test_account_recovery.py
with @tuliocasagrande
missing:
=> [#927] Add recovery code mail template

service/pixelated/account_recovery.py, service/pixelated/assets/recovery.mail.en-US, service/pixelated/assets/recovery.mail.pt-BR, service/pixelated/resources/backup_account_resource.py, service/pixelated/resources/login_resource.py, service/pixelated/support/language.py, service/test/unit/resources/test_backup_account_resource.py, service/test/unit/resources/test_login_resource.py, service/test/unit/support/test_language.py, service/test/unit/test_account_recovery.py
Related with #927 
with @deniscostadsc
=> Recovery code email translations and formatting

service/pixelated/account_recovery.py, service/test/unit/test_account_recovery.py
=> [#927] Uses internal email date method for consistency

service/test/functional/features/steps/login.py, web-ui/src/login/opensans.css, web-ui/webpack.production.config.js
Refresh before logout during functional tests.  Also fix javascript error and remove console logs on production.
=> Logout refresh
