README.md
Previously it was assuming that you were always running the pixelated-user-agent from inside the /vagrant folder.
Now we will make sure everyone is able to run it, wherever they are.
=> Updating certificate folder

service/pixelated/adapter/services/mail_service.py, service/test/unit/adapter/test_mail_service.py
Fixes #374 although possibly not in the best way. We considered doing this in JavaScript. We also considered removing the concept of an 'unread' sent mail altogether. The problem with the latter would be if the user sets up an auto-reply. Would appreciate some guidance.
=> Eli: Marking sent emails as read

service/.gitignore, web-ui/app/js/mail_view/ui/recipients/recipients.js, web-ui/app/scss/_mixins.scss, web-ui/app/templates/compose/recipients.hbs
The pull request also fixes the `navigation-handler` not hiding properly.
=> Align second line of email addresses to the beginning of the first line

service/pixelated/adapter/model/mail.py, service/requirements.txt
cryptography is now a hard dependency, so we are removing the use of
pycryptopp.
=> [fix] remove pycryptopp dependency

web-ui/app/js/mail_view/ui/mail_view.js, web-ui/app/scss/style.scss, web-ui/app/scss/views/_security-labels.scss, web-ui/app/templates/mails/full_view.hbs, web-ui/test/spec/mail_view/ui/mail_view.spec.js
This change refactor the stylesheet of security labels. Now it's
following the BEM naming conventions. Also, as the code is pretty
coupled between css and js, it was necessary some changes on javascript
code to keep the previous i18n key and rename the css classes.
=> Issue #647: Refactor security labels stylesheet

service/pixelated/resources/__init__.py, service/test/unit/resources/test_helpers.py
I noticed that `respond_json` and `respond_json_deferred` were calling `addRawHeader` but passing a list as the argument, yielding the following HTTP header: `Content-Type: ['application/json']`.
This updates to use `setRawHeaders` instead, which does accept an array as the second parameter.
=> Updated calls to addRawHeader to use setRawHeaders

service/pixelated/adapter/services/mail_sender.py, service/test/unit/adapter/services/test_mail_sender.py
`MailSender.sendmail` modifies the `InputMail` headers while sending. This breaks the expectation of the parent that the `InputMail` will be saved unmodified. A simple `deepcopy` does the trick.
=> Issue 695: Show all recipients in mail sent folder

service/pixelated/resources/__init__.py, service/pixelated/resources/root_resource.py, service/test/unit/resources/test_root_resource.py
During the cryptohack virtual hack night last night, I spent a bit of time going over some of the hiccups I experienced in trying to get a development environment up and running, reorienting myself with twisted and getting familiar with the structure of the project. I came across some fairly gnarly stack traces that would happen between starting the user agent and the `user agent is ready` message appearing:
```
2016-05-26 04:38:35 [twisted] CRITICAL Unhandled Error
Traceback (most recent call last):
File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/web/http.py", line 1688, in lineReceived
self.allContentReceived()
File "/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/web/http.py", line 1767, in allContentReceived …
```
=> RootResource should return 503 during startup

web-ui/app/scss/views/_mail-list.scss
fixes #743
For mail items without tags the link to open the mail is not expanded,
therefore it has to be done via CSS
=> Make whole mail item without tags clickable

service/test/unit/config/test_site.py
I bumped into this problem where trial would try to clean up after
running the SiteTest and run into an error
'RememberedInvocation has no attribute "_implied"'
That happened because mockito is strict with the set of functions
it's mock accepts and _implied doesn't exist. It didn't really make
sense in this test context so I've adapted the test to use MagicMock
instead and now the test pass without problems.
=> Fixed mockito conflict with zope

service/pixelated/resources/root_resource.py
There are only two possibilities currently:
- The static files are at web-ui/dist
- The static files are installed by the debian package
at /usr/share/pixelated-user-agent
This change removed the third non-existent possibility that was
causing errors sometimes in a new environment (service/web-ui/dist)
=> Simplifies the get_static_folder on RootResource

service/pixelated/config/sessions.py, service/test/unit/config/test_sessions.py
When the upload of the user key fails (i.e. Timeout), the session was being held
in memory, preventing the user from trying again.
Related with: #815, #889
=> Close session when UploadKeyError occurs

web-ui/package.json
This is so that, when developing, if there is a change in javascript, the bundle recompiles automatically. 
This is part of the transition to webpack. Eventually, we can try to use webpack-dev-server for development.
=> Adds js to watch command

debian/control
We're having issues with python-gnupg when we are creating the image for piuparts testing.
```
17:14:45.477   The following extra packages will be installed:
17:14:45.477     python-gnupg
17:14:45.477   The following NEW packages will be installed:
17:14:45.477     python-gnupg
17:14:45.477   0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
17:14:45.477   1 not fully installed or removed.
17:14:45.477   Need to get 14.7 kB of archives.
17:14:45.478   After this operation, 92.2 kB of additional disk space will be used.
17:14:45.478   Err http://debian.mirror.iphh.net/debian/ jessie/main python-gnupg all 0.3.6-1
17:14:45.478     Could not connect to 213.73.97.49:3142 (213.73.97.49), connection timed out
17:14:45.478   E: Failed to fetch …
```
=> Remove python-gnupg debian package as dependency

provisioning/modules/pixelated/manifests/source/install_useragent.pp
Should fix the need for activating the virtualenv manually in vagrant.
=> Removes old virutalenv that is no longer being used

service/pixelated/config/leap.py, service/pixelated/config/sessions.py, service/test/unit/config/test_leap.py, service/test/unit/config/test_sessions.py
Something I noticed while testing #889.
I changed `raise e` to `raise`, so we'll see the traceback where the exception started.
=> Keep exception context

debian/pixelated-user-agent.postinst
After upgrading Pixelated User Agent package this script will restart the
server in order to have the newest code running.
This change makes explicit the relationship between pixelated-user-agent and pixelated-server.
It is not necessarily good, so we are planning to unify pixelated-service and pixelated-user-agent on the feature to make pixelated-user-agent as a service.
For now it will solve our current problem about restart pixelated-service after the pixelated-user-agent updated package.
=> Adds postinstall scritp to restart pixelated-server

web-ui/app/js/dispatchers/right_pane_dispatcher.js, web-ui/app/js/mail_view/ui/spinner.js, web-ui/app/js/page/pix_logo.js, web-ui/app/js/views/templates.js, web-ui/app/scss/base/_colors.scss, web-ui/app/scss/style.scss, web-ui/app/scss/views/_spinner.scss, web-ui/app/templates/mails/spinner.hbs, web-ui/test/spec/dispatchers/right_pane_dispatcher.spec.js, web-ui/test/spec/mail_view/ui/spinner.spec.js, web-ui/test/spec/page/pix_logo.spec.js
We added the spinner just before load the first part of the email (header with the title). We will create a new issue to make the email loads at once.
related with #657
with @tuliocasagrande
=> Add spinner before loading an email or draft.

service/pixelated/config/logger.py
The `Unhandled error in Deferred` events were not being correctly logged because of an invalid `log_format` attribute.
See: #952
=> Unhandled error

service/pixelated/account_recovery.py, service/pixelated/application.py, service/pixelated/authentication.py, service/pixelated/resources/backup_account_resource.py, service/pixelated/resources/login_resource.py, service/pixelated/resources/root_resource.py, service/requirements.txt, service/test/unit/resources/test_backup_account_resource.py, service/test/unit/resources/test_login_resource.py, service/test/unit/test_account_recovery.py, service/test/unit/test_application.py, service/test/unit/test_authentication.py
This is the first part of the Account Recovery implementation, to allow existing accounts to add a recovery code to recover the password. These changes are only to persist the recovery code in webapp. It's not yet possible to login with the recovery code.
We are using a new branch of bitmask dev while we wait for this MR: https://0xacab.org/leap/bitmask-dev/merge_requests/79
Related with: https://github.com/pixelated/pixelated-user-agent/issues/924
with @anikarni
=> [#924] Implements update recovery code through bitmask

service/pixelated/resources/account_recovery_resource.py, service/pixelated/resources/root_resource.py, service/test/unit/resources/test_account_recovery_resource.py, web-ui/app/locales/en_US/translation.json, web-ui/app/locales/pt_BR/translation.json, web-ui/config/protected-assets-webpack.js, web-ui/package.json, web-ui/src/account_recovery/account_recovery.html, web-ui/src/account_recovery/account_recovery.js, web-ui/src/account_recovery/page.js, web-ui/src/account_recovery/page.scss, web-ui/src/account_recovery/page.spec.js, web-ui/test/integration/translations.spec.js, web-ui/webpack.config.js, web-ui/webpack.production.config.js
This PR creates the resource for the forgot password page, but does not implement anything on the page yet (just the header and footer, as bellow).
Related with #932
=> Forgot password page

web-ui/app/locales/en_US/translation.json, web-ui/src/account_recovery/forms/admin_recovery_code_form.js, web-ui/src/account_recovery/forms/admin_recovery_code_form.spec.js, web-ui/src/account_recovery/forms/user_recovery_code_form.js, web-ui/src/account_recovery/forms/user_recovery_code_form.spec.js, web-ui/src/account_recovery/page.js, web-ui/src/account_recovery/page.scss, web-ui/src/account_recovery/page.spec.js, web-ui/test/integration/translations.spec.js
So far, the admin code form is displayed on loading page, and, when clicking next, it show the title for the next form (see gif bellow).
TODO:
=> Adds admin code form and logic for next step of recovery form

Makefile, service/requirements.txt, service/test/unit/config/test_site.py
Upgrades Twisted version to the latest available (17.1.0) which is also the version used by Leap.  According to the docs for Trial - https://twistedmatrix.com/documents/current/core/howto/trial.html - now we need to export - PYTHONPATH="$PYTHONPATH:`pwd`/.." in the `service` directory to make the tests work.
=> [#1018] Upgrades twisted from 16.1.1 to 17.1.0

service/pixelated/resources/account_recovery_resource.py, service/test/unit/resources/test_account_recovery_resource.py, web-ui/src/account_recovery/new_password_form/new_password_form.js, web-ui/src/account_recovery/new_password_form/new_password_form.spec.js, web-ui/src/account_recovery/page.js, web-ui/src/account_recovery/page.spec.js, web-ui/src/account_recovery/user_recovery_code_form/user_recovery_code_form.js, web-ui/src/account_recovery/user_recovery_code_form/user_recovery_code_form.spec.js, web-ui/src/backup_account/backup_email/backup_email.js, web-ui/src/backup_account/backup_email/backup_email.spec.js, web-ui/src/common/util.js, web-ui/src/common/util.spec.js
This starts the implementation of login with the recovery code.
To do:
=> [#935] Sends user recovery code and password to account recovery endpoint

Makefile, provisioning/modules/chromedriver/manifests/init.pp, provisioning/modules/pixelated/manifests/source.pp
Fix functional test step `Then I should see the fancy interstitial`, that's not working properly with newer versions of chromedriver.
Since the debian repo doesn't provide old versions of chromium, we're [shipping][1] our own local copies:
```
$ chromedriver --version
ChromeDriver 2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320)
```
```
$ google-chrome --version
Google Chrome 54.0.2840.100
```
[1]: https://github.com/pixelated/pixelated-user-agent/releases/tag/1.0_beta1
=> Ship our local version of google-chrome and chromedriver
